commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: jh-magento-ce-1.8.0.0
        version: 1.8.0.0
        source:
          url: git@bitbucket.org:jhhello/magento-ce-1.8.0.0.git
          type: git
          reference: 1.0.0
        #process-timeout: 600
        extra:
          #standard magento sample data - http://www.magentocommerce.com/downloads/assets/1.6.1.0/magento-sample-data-1.6.1.0.tar.gz
          sample-data: sample-data-1.6.1.0

      - name: jh-magento-ce-1.8.1.0
        version: 1.8.1.0
        source:
          url: git@bitbucket.org:jhhello/magento-ce-1.8.1.0.git
          type: git
          reference: 1.0.0
        extra:
          #standard magento sample data - http://www.magentocommerce.com/downloads/assets/1.6.1.0/magento-sample-data-1.6.1.0.tar.gz
          sample-data: sample-data-1.6.1.0

      - name: jh-magento-ee-1.12.0.0
        version: 1.12.0.0
        source:
          url: git@bitbucket.org:jhhello/magento-ee-1.12.0.0.git
          type: git
          reference: 1.0.0

      - name: jh-magento-ee-1.12.0.2
        version: 1.13.0.2
        source:
          url: git@bitbucket.org:jhhello/magento-ee-1.12.0.2.git
          type: git
          reference: 1.0.0

      - name: jh-magento-ee-1.13.0.2
        version: 1.13.0.2
        source:
          url: git@bitbucket.org:jhhello/magento-ee-1.13.0.2.git
          type: git
          reference: 1.0.0

      - name: jh-magento-ee-1.13.1.0
        version: 1.13.1.0
        source:
          url: git@bitbucket.org:jhhello/magento-ee-1.13.1.0.git
          type: git
          reference: 1.0.0

      - name: jh-magento-ee-1.14.0.0
        version: 1.14.0.0
        source:
          url: git@bitbucket.org:jhhello/magento-ee-1.14.0.0.git
          type: git
          reference: 1.0.0

    installation:
      defaults:
        currency: GBP
        locale: en_US
        timezone: Europe/London
        use_secure: no
        use_rewrites: yes
        session_save: files
        admin_username: wearejh
        admin_firstname: John
        admin_lastname: Doe
        admin_password: password123
        admin_frontname: admin
        admin_email: john.doe@example.com

    #example of how to add demo data packages, if we decide to host our own
    demo-data-packages:
      - name: jh-sample-data-ce-1.0
        version: 1.0
        dist:
          url: http://wearejh.com/magento/sampledata/ce/jh-sample-data-cd-1.0.tar.gz
          type: tar
