commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: jh-magento-ce-1.8.0.0
        version: 1.8.0.0
        source:
          url: git@bitbucket.org:jhhello/magento_ce_1.8.0.0.git
          type: git
          reference: master

      - name: jh-magento-ee-1.13.0.2
        version: 1.13.0.2
        source:
          url: git@bitbucket.org:jh_hello/magento_ee_1.13.0.2.git
          type: git
          reference: master

    defaults:
      currency: GBP
      locale: en_US
      timezone: Europe/London
      use_secure: no
      use_rewrites: yes
      session_save: files
      admin_username: wearejh
      admin_firstname: John
      admin_lastname: Doe
      admin_password: password123
      admin_frontname: admin
      admin_email: john.doe@example.com