commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: jh-magento-ce-1.9.0.1
        version: 1.9.0.1
        source:
          url: https://github.com/adam-paterson/magento-ce-1.9.0.1.git
          type: git
          reference: 1.0.0
        #process-timeout: 600
        extra:
          #standard magento sample data - http://www.magentocommerce.com/downloads/assets/1.6.1.0/magento-sample-data-1.6.1.0.tar.gz
          sample-data: sample-data-1.9.0.0

    installation:
      defaults:
        currency: GBP
        locale: en_US
        timezone: Europe/London
        use_secure: no
        use_rewrites: yes
        session_save: files
        admin_username: wearejh
        admin_firstname: John
        admin_lastname: Doe
        admin_password: password123
        admin_frontname: admin
        admin_email: john.doe@example.com

    #example of how to add demo data packages, if we decide to host our own
    demo-data-packages:
      - name: jh-sample-data-ce-1.0
        version: 1.0
        dist:
          url: http://wearejh.com/magento/sampledata/ce/jh-sample-data-cd-1.0.tar.gz
          type: tar
